sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t salgoan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true salgoan/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-938449754360"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_key_id: "$AWS_SECRET_KEY"  